# service description
services:

  egroo-api-test:
    image: jihadkhawaja/mobilechat-server:latest
    entrypoint: ["dotnet", "Egroo.Server.dll"]
    container_name: egroo-api-test
    hostname: egroo-api-test
    restart: unless-stopped
    networks:
      - internal
    # ports:
    #   - "8080"

networks:
  internal:
    external: true
