# service description
services:

  egroo-api:
    image: jihadkhawaja/egroo-server-prod:${API_IMAGE_TAG:-latest}
    entrypoint: ["dotnet", "Egroo.Server.dll"]
    container_name: egroo-api
    hostname: egroo-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
    networks:
      - internal

  egroo-web:
    image: jihadkhawaja/egroo-client-prod:${WEB_IMAGE_TAG:-latest}
    entrypoint: ["dotnet", "Egroo.dll"]
    container_name: egroo-web
    hostname: egroo-web
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.3"
    networks:
      - internal

networks:
  internal:
    external: true
