# service description
services:

  egroo-api:
    image: jihadkhawaja/mobilechat-server-prod:latest
    entrypoint: ["dotnet", "Egroo.Server.dll"]
    container_name: egroo-api
    hostname: egroo-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
    networks:
      - internal
    # ports:
    #   - "8080"

  egroo-web:
    image: jihadkhawaja/mobilechat-wasm-prod:latest
    entrypoint: ["dotnet", "Egroo.dll"]
    container_name: egroo-web
    hostname: egroo-web
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.3"
    networks:
      - internal
    # ports:
    #   - "8080"

networks:
  internal:
    external: true
