//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xamarinchatsr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xamarinchatsr.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string anonymous {
            get {
                return ResourceManager.GetString("anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string bright {
            get {
                return ResourceManager.GetString("bright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Message.
        /// </summary>
        internal static string chatenterurmsg {
            get {
                return ResourceManager.GetString("chatenterurmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string chatinputplaceholder {
            get {
                return ResourceManager.GetString("chatinputplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain open to others, respect their ideas, opinions.
        /// </summary>
        internal static string chattext {
            get {
                return ResourceManager.GetString("chattext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your display name.
        /// </summary>
        internal static string enteryourdisplayname {
            get {
                return ResourceManager.GetString("enteryourdisplayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged As.
        /// </summary>
        internal static string loggedas {
            get {
                return ResourceManager.GetString("loggedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Chat.
        /// </summary>
        internal static string pagechatitle {
            get {
                return ResourceManager.GetString("pagechatitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string pagehometitle {
            get {
                return ResourceManager.GetString("pagehometitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and Review App.
        /// </summary>
        internal static string rateandreviewapp {
            get {
                return ResourceManager.GetString("rateandreviewapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share App.
        /// </summary>
        internal static string shareapp {
            get {
                return ResourceManager.GetString("shareapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string tabchattitle {
            get {
                return ResourceManager.GetString("tabchattitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string tabhometitle {
            get {
                return ResourceManager.GetString("tabhometitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string tabsettingstitle {
            get {
                return ResourceManager.GetString("tabsettingstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users in chat.
        /// </summary>
        internal static string usersinchat {
            get {
                return ResourceManager.GetString("usersinchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find new friends.
        /// </summary>
        internal static string walkthrought1 {
            get {
                return ResourceManager.GetString("walkthrought1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with others and share your thoughts while maintaining privacy.
        /// </summary>
        internal static string walkthrought2 {
            get {
                return ResourceManager.GetString("walkthrought2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should we call you.
        /// </summary>
        internal static string whatshouldwecallyou {
            get {
                return ResourceManager.GetString("whatshouldwecallyou", resourceCulture);
            }
        }
    }
}
