name: Docker

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # docker-compose check
      - name: docker-compose checking
        working-directory: ./src/Egroo.Server
        run: docker-compose up -d
