name: MSTest

permissions:
  contents: read

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore src/Egroo.Server.Test/Egroo.Server.Test.csproj

      - name: Build
        run: dotnet build --no-restore --configuration Release src/Egroo.Server.Test/Egroo.Server.Test.csproj

      - name: Test
        run: dotnet test --no-build --configuration Release --logger trx --results-directory TestResults src/Egroo.Server.Test/Egroo.Server.Test.csproj

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: TestResults/*.trx
